version: '3.1'
services:

  db:
    image: postgres
    restart: always
    container_name: postgresql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - type: bind
        source: ./wormhole
        target: /wormhole
      - type: volume
        source: postgresql_vol
        target: /var/lib/postgresql/data
    networks:
      - ${NETWORK}

volumes:
  postgresql_vol: